spring:
  application:
    name: service-consumer
  cloud:
    stream:
      function.definition: testConsumer
      bindings:
        testConsumer-in-0:
          destination: test.topic
          binder: rabbit
          group: test-consumer-group
      binders:
        rabbit:
          type: rabbit
          defaultCandidate: false
          inheritEnvironment: false
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    loggers.enabled: true
    elastic.enabled: true
  metrics:
    export:
      elastic:
        enabled: true
        host: http://localhost:9200
        auto-create-index: true
        step: 1m

---
spring:
  profiles: docker-compose
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          defaultCandidate: false
          inheritEnvironment: false
          environment:
            spring:
              rabbitmq:
                host: rabbitmq
                port: 5672
                username: guest
                password: guest
management:
  endpoints.web.exposure.include: "*"
  endpoint:
    loggers.enabled: true
    elastic.enabled: true
  metrics:
    export:
      elastic:
        enabled: true
        host: http://elasticsearch:9200
        auto-create-index: true
        step: 1m